[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    mathieucarbou/ESPAsyncWebServer
    bblanchon/ArduinoJson
    lsatan/SmartRC-CC1101-Driver-Lib
    marvinroger/AsyncMqttClient

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = -DCORE_DEBUG_LEVEL=3
